<script setup lang="ts">
import { useHead } from "@unhead/vue"

import Footer from "@/layout/components/Footer/index.vue"
import HeaderAbout from "@/layout/components/HeaderAbout.vue"

defineOptions({
  name: "TermsOfService"
})

useHead({
  title: "Terms of service - Daily Horoscope",
  meta: [
    {
      name: "description",
      content:
        "Review our terms and conditions to ensure compliance and enjoy the best experience on our site."
    }
  ]
})

const termsOfService = [
  {
    title: "Acceptance of Terms",
    content:
      "By using our site, you accept these Terms of Use in full. If you disagree with any part, please refrain from using our website."
  },
  {
    title: "Use of Content",
    content:
      "The content, including horoscopes and predictions, is generated by ChatGPT and intended for entertainment purposes only. We do not guarantee the accuracy, completeness, or usefulness of any information provided."
  },
  {
    title: "Intellectual Property",
    content:
      "All content on this site, including text, graphics, logos, and images, is the property of dailyhoroscope.fun and is protected by copyright and trademark laws. Unauthorized use is prohibited."
  },
  {
    title: "User Conduct",
    content:
      "You agree not to use the site for any illegal or harmful activities. This includes uploading or transmitting any malicious software or engaging in any form of data mining."
  },
  {
    title: "Disclaimer of Warranties",
    content: `The site is provided "as is" without any warranties of any kind. We disclaim all warranties, express or implied, including but not limited to the accuracy or reliability of content.`
  },
  {
    title: "Limitation of Liability",
    content:
      "In no event shall dailyhoroscope.fun be liable for any indirect, incidental, or consequential damages arising out of or in connection with the use of our site."
  },
  {
    title: "Indemnification",
    content:
      "You agree to indemnify and hold harmless dailyhoroscope.fun and its affiliates from any claims, damages, or expenses arising from your use of the site."
  },
  {
    title: "Modification of Terms",
    content:
      "We reserve the right to modify these terms at any time. Continued use of the site after any changes constitutes acceptance of the new terms."
  }
]
</script>

<template>
  <HeaderAbout title="Terms of service" />
  <div class="app-main">
    <div class="app-content">
      <div class="item-wrapper">
        <h2 class="item-title">Welcome to dailyhoroscope.fun.</h2>
        <p class="item-content">
          Welcome to dailyhoroscope.fun. By accessing or using our website, you agree to comply with
          and be bound by the following terms and conditions. Please read them carefully.
        </p>
      </div>

      <div v-for="(item, index) in termsOfService" :key="index" class="item-wrapper">
        <h2 class="item-title">
          <span class="item-index">{{ index + 1 }}</span>
          {{ item.title }}
        </h2>
        <p class="item-content">{{ item.content }}</p>
      </div>
    </div>
  </div>
  <Footer />
</template>

<style lang="scss" scoped>
.app-main {
  padding-top: 50px;
  max-width: 1200px;
  margin: 0 auto;

  .item-wrapper {
    margin-bottom: 25px;

    .item-title {
      font-family: "Rubik One";
      line-height: normal;
      margin-bottom: 18px;

      .item-index {
        width: 20px;
        height: 20px;
        line-height: 1;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-family: Roboto;
        background-color: #000;
        font-size: 14px;
        font-weight: 600;
        color: #fff;
        border-radius: 50%;
      }
    }

    .item-content {
      font-family: Roboto;
      font-weight: 500;
      line-height: 1.5;
    }

    &:last-of-type {
      margin-bottom: 0;
    }
  }
}
</style>
