<script setup lang="ts">
import type { ResourceListType } from "@/configs/constants"

interface Props {
  resourceList: ResourceListType
  webConfig: WebConfig
}

withDefaults(defineProps<Props>(), {})
</script>

<template>
  <footer class="footer">
    <div class="pc-top">
      <div class="footer-item about-us">
        <p class="item-title">About us</p>
        <p class="item-content">{{ webConfig.aboutUs }}</p>
      </div>
      <div class="pc-right">
        <div class="footer-item resource">
          <p class="item-title">Resource</p>
          <p
            v-for="(item, index) in resourceList"
            :key="index"
            class="item-content"
            @click="$emit('resource-click', item.path)"
          >
            {{ item.name }}
          </p>
        </div>
        <div class="footer-item">
          <p class="item-title">Contact us</p>
          <a class="item-content" :href="`mailto:${webConfig.appEmail}`">
            {{ webConfig.appEmail }}
          </a>
        </div>
      </div>
    </div>
    <div class="footer-item copyright">
      <p class="item-content">
        All predictions are generated by ChatGPT and are for entertainment purposes only
      </p>
      <p class="item-content">Copyright © 2024 {{ webConfig.appUrl }}. All Rights Reserved.</p>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
.footer {
  position: relative;
  display: flex;
  flex-direction: column;
  background: #333;
  color: #fff;
  $pc-margin: calc((100% - $container-width) / 2);

  .footer-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 16px 24px;
    border-bottom: 1px solid #434343;

    .item-title {
      font-weight: 600;
      margin-bottom: 20px;
    }

    .item-content {
      text-align: center;
      line-height: normal;
      font-size: 14px;
    }

    // 资源
    &.resource {
      .item-content {
        @include hover-effect(1);

        &:not(:last-of-type) {
          margin-bottom: 20px;
        }
      }
    }

    // 版权声明
    &.copyright {
      color: rgba(255, 255, 255, 0.6);

      .item-content {
        font-size: 10px;
        line-height: 18px;
      }
    }
  }

  .pc-top {
    position: relative;
    width: 100%;
    display: flex;
    padding: 0 $pc-margin;
    &::after {
      content: "";
      position: absolute;
      bottom: 0;
      left: $pc-margin;
      right: $pc-margin;
      height: 1px;
      background-color: #434343;
    }

    .about-us {
      width: 50%;
      border-bottom: none;
      align-items: flex-start;
      padding: 16px 120px;
    }
    .pc-right {
      width: 50%;

      .footer-item {
        border-bottom: none;
        align-items: flex-start;
        padding: 16px 120px;
      }
    }
  }
}
</style>
