<script setup lang="ts">
import { useRouter } from "vue-router"

import { resourceList } from "@/config/constants"
import { useAppStore } from "@/store/modules/app"

defineOptions({
  name: "DesktopFooter"
})

const appStore = useAppStore()
const { webConfig } = appStore

const router = useRouter()
</script>

<template>
  <footer class="footer">
    <div class="footer-top">
      <div class="top-item">
        <div class="footer-item about-us">
          <p class="item-title">About us</p>
          <p class="item-content">{{ webConfig.aboutUs }}</p>
        </div>
      </div>
      <div class="top-item">
        <div class="footer-item resource">
          <p class="item-title">Resource</p>
          <p
            v-for="(item, index) in resourceList"
            :key="index"
            class="item-content"
            @click="router.push(item.path)"
          >
            {{ item.name }}
          </p>
        </div>
        <div class="footer-item">
          <p class="item-title">Contact us</p>
          <a class="item-content" :href="`mailto:${webConfig.appEmail}`">
            {{ webConfig.appEmail }}
          </a>
        </div>
      </div>
    </div>

    <div class="footer-bottom footer-item copyright">
      <p class="item-content">
        All predictions are generated by ChatGPT and are for entertainment purposes only
      </p>
      <p class="item-content">Copyright © 2024 {{ webConfig.appUrl }}. All Rights Reserved.</p>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
.footer {
  position: relative;
  background: #333;
  color: #fff;
  font-family: "Roboto";

  .footer-top {
    border-bottom: 1px solid #434343;
    display: flex;

    .top-item {
      flex: 1;
      padding: 0 calc((100% - 720px) / 4);
    }
  }

  .footer-bottom {
    display: flex;
    align-items: center;
  }

  .footer-item {
    display: flex;
    flex-direction: column;
    padding: 32px 24px;

    .item-title {
      font-size: 18px;
      font-weight: 600;
      margin-bottom: 20px;
    }

    .item-content {
      line-height: normal;
    }

    &.about-us {
      .item-content {
        line-height: 2;
      }
    }

    &.resource {
      .item-content {
        @include hover-effect(1);

        &:not(:last-of-type) {
          margin-bottom: 20px;
        }
      }
    }

    &.copyright {
      color: rgba(255, 255, 255, 0.6);

      .item-content {
        line-height: 2;
      }
    }
  }
}

@media (min-width: 1200px) {
  .footer {
    padding: 0 calc((100% - 1200px) / 2);
  }
}
</style>
