<script setup lang="ts">
import { useRouter } from "vue-router"

import { resourceList } from "@/configs/constants"
import { useAppStore } from "@/stores/modules/app"

defineOptions({
  name: "BaseFooter"
})

const appStore = useAppStore()
const { webConfig } = appStore
const router = useRouter()
</script>

<template>
  <footer class="footer">
    <div class="footer-item">
      <p class="item-title">About us</p>
      <p class="item-content">{{ webConfig.aboutUs }}</p>
    </div>
    <div class="footer-item resource">
      <p class="item-title">Resource</p>
      <p
        v-for="(item, index) in resourceList"
        :key="index"
        class="item-content"
        @click="router.push(item.path)"
      >
        {{ item.name }}
      </p>
    </div>
    <div class="footer-item">
      <p class="item-title">Contact us</p>
      <a class="item-content" :href="`mailto:${webConfig.appEmail}`">
        {{ webConfig.appEmail }}
      </a>
    </div>
    <div class="footer-item copyright">
      <p class="item-content">
        All predictions are generated by ChatGPT and are for entertainment purposes only
      </p>
      <p class="item-content">Copyright © 2024 {{ webConfig.appUrl }}. All Rights Reserved.</p>
    </div>
  </footer>
</template>

<style lang="scss" scoped>
.footer {
  position: relative;
  display: flex;
  flex-direction: column;
  background: #333;
  color: #fff;
  font-family: "Roboto";

  .footer-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 16px 24px;

    &:not(:last-of-type) {
      border-bottom: 1px solid #434343;
    }

    .item-title {
      font-weight: 600;
      margin-bottom: 20px;
    }

    .item-content {
      text-align: center;
      line-height: normal;
      font-size: 14px;
    }

    &.resource {
      .item-content {
        @include hover-effect(1);

        &:not(:last-of-type) {
          margin-bottom: 20px;
        }
      }
    }

    &.copyright {
      color: rgba(255, 255, 255, 0.6);

      .item-content {
        font-size: 10px;
        line-height: 18px;
      }
    }
  }
}
</style>
