// 项目配置
const APPTITLE = import.meta.env.VITE_APPTITLE
const AD_CLIENT = import.meta.env.VITE_AD_CLIENT

export const defaultSettings = {
  /** 广告配置 */
  adSense: {
    // 加载 AdSense 脚本的 URL
    scriptUrl: `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${import.meta.env.PROD ? AD_CLIENT : "ca-google"}`,
    // 广告位配置
    home_1: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": AD_CLIENT,
      "data-ad-slot": "",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    },
    home_2: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": AD_CLIENT,
      "data-ad-slot": "",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    },
    home_3: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": AD_CLIENT,
      "data-ad-slot": "5216268932",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    },
    content_1: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": "ca-pub-8158555231596181",
      "data-ad-slot": "4429670998",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    },
    content_2: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": "ca-pub-8158555231596181",
      "data-ad-slot": "6607082089",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    },
    content_3: {
      class: "adsbygoogle",
      style: "display:block",
      "data-ad-client": "ca-pub-8158555231596181",
      "data-ad-slot": "7650860583",
      "data-ad-format": "auto",
      "data-full-width-responsive": "true"
    }
  },
  /** firebase 配置 */
  firebase: {
    apiKey: "AIzaSyBcS3cwlUXpK99s0FiNLcdhiTqTbqa8pRo",
    authDomain: "webs-58a8d.firebaseapp.com",
    projectId: "webs-58a8d",
    storageBucket: "webs-58a8d.appspot.com",
    messagingSenderId: "730684174767",
    appId: "1:730684174767:web:98cad94ee478557c0c3f5a",
    measurementId: "G-4MPLF3JL2K"
  },
  /** 关于我们 */
  aboutUs: `Welcome to DailyHoroscope! We offer daily zodiac insights and cosmic guidance to help you explore your destiny and make informed choices.`,
  /** Resource */
  resource: [
    {
      name: "Daily horoscope",
      path: "/"
    },
    {
      name: "Weekly horoscope",
      path: "/weekly-horoscope"
    },
    {
      name: "Monthly horoscope",
      path: "/monthly-horoscope"
    },
    {
      name: "Yearly horoscope",
      path: "/yearly-horoscope"
    },
    {
      name: "Terms of service",
      path: "/terms-of-service"
    },
    {
      name: "Privacy policy",
      path: "/privacy-policy"
    }
  ],
  /** 邮箱 */
  email: "dailyhoroscope.support@gmail.com",
  /** 版权声明 */
  copyright: [
    `All predictions are generated by ChatGPT and are for entertainment purposes only`,
    `Copyright © 2024 ${APPTITLE}. All Rights Reserved.`
  ]
}
